// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmD0nTwUM4KvGArUUbedJer88JJqLLp2Q',
    appId: '1:67018964338:android:198a8cf071f6fe588331eb',
    messagingSenderId: '67018964338',
    projectId: 'stepexpert-202a7',
    storageBucket: 'stepexpert-202a7.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyx9QboLHpbFPqNloA4aPoANzaEZUB5CY',
    appId: '1:67018964338:web:f12d1e74f91dcf258331eb',
    messagingSenderId: '67018964338',
    projectId: 'stepexpert-202a7',
    authDomain: 'stepexpert-202a7.firebaseapp.com',
    storageBucket: 'stepexpert-202a7.firebasestorage.app',
    measurementId: 'G-HPJLWR8QWX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1iekC67bfsw8Y6cODfnnuLCFJXm5C7NE',
    appId: '1:67018964338:ios:577b558389dde4c08331eb',
    messagingSenderId: '67018964338',
    projectId: 'stepexpert-202a7',
    storageBucket: 'stepexpert-202a7.firebasestorage.app',
    iosBundleId: 'com.example.stepexpertx',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1iekC67bfsw8Y6cODfnnuLCFJXm5C7NE',
    appId: '1:67018964338:ios:577b558389dde4c08331eb',
    messagingSenderId: '67018964338',
    projectId: 'stepexpert-202a7',
    storageBucket: 'stepexpert-202a7.firebasestorage.app',
    iosBundleId: 'com.example.stepexpertx',
  );
}
