// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJTtui8gXS8kM9yDCYpXa8XgcvV-9Toq4',
    appId: '1:260227433666:android:36c1e7a2d7e323ff14e75b',
    messagingSenderId: '260227433666',
    projectId: 'stepexpert-bed14',
    storageBucket: 'stepexpert-bed14.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMtQICvRm-kZzFlo0RQaC01eqVxCIvwA0',
    appId: '1:260227433666:web:5ba788793e8751fa14e75b',
    messagingSenderId: '260227433666',
    projectId: 'stepexpert-bed14',
    authDomain: 'stepexpert-bed14.firebaseapp.com',
    storageBucket: 'stepexpert-bed14.firebasestorage.app',
    measurementId: 'G-ZV81CGLLRD',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_THpMwrzqIa3ruHlLFJTg-AC3yjcy2QA',
    appId: '1:260227433666:ios:6169095498e6a74214e75b',
    messagingSenderId: '260227433666',
    projectId: 'stepexpert-bed14',
    storageBucket: 'stepexpert-bed14.firebasestorage.app',
    iosBundleId: 'com.example.stepexpert',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_THpMwrzqIa3ruHlLFJTg-AC3yjcy2QA',
    appId: '1:260227433666:ios:6169095498e6a74214e75b',
    messagingSenderId: '260227433666',
    projectId: 'stepexpert-bed14',
    storageBucket: 'stepexpert-bed14.firebasestorage.app',
    iosBundleId: 'com.example.stepexpert',
  );

}